Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = mk.DataFrame(
    {
        "img": img_col,
        "label": ["boombox", "truck", "dog"],
        "id": id_col, 
    }
)
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m df [38;5;241m=[39m [43mmk[49m[38;5;241m.[39mDataFrame(
[1;32m      2[0m     {
[1;32m      3[0m         [38;5;124m"[39m[38;5;124mimg[39m[38;5;124m"[39m: img_col,
[1;32m      4[0m         [38;5;124m"[39m[38;5;124mlabel[39m[38;5;124m"[39m: [[38;5;124m"[39m[38;5;124mboombox[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mtruck[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mdog[39m[38;5;124m"[39m],
[1;32m      5[0m         [38;5;124m"[39m[38;5;124mid[39m[38;5;124m"[39m: id_col, 
[1;32m      6[0m     }
[1;32m      7[0m )
[1;32m      8[0m df

[0;31mNameError[0m: name 'mk' is not defined
NameError: name 'mk' is not defined

